GOOGLE_API_KEY = "AIzaSyAbB2Q68OTrzI0PhAdcYjn2DQLzIJIH1ww"
PINECONE_API_KEY = "9751daec-0359-4afc-80a8-c1c0d9179cc1"
PINECONE_ENV = "asia-southeast1-gcp-free"
OPENAI_API_KEY = ""
GOOGLE_KEY_PATH = "application_default_credentials.json"